[Fan1]
low_temp=55
high_temp=75
speed_curve=exponential
always_full_speed=false

[Fan2]
low_temp=50
high_temp=85
speed_curve=exponential
always_full_speed=false
sensors=slot:1
exp_pow=2.5

[Fan3]
low_temp=50
high_temp=85
speed_curve=exponential
always_full_speed=false
sensors=slot:3
exp_pow=2.5

[Fan4]
low_temp=55
high_temp=75
speed_curve=exponential
always_full_speed=false
